variable "eso_namespace" {
  description = "Namespace External Secrets runs in."
  type        = string
  default     = "external-secrets"
}

variable "eso_service_account" {
  description = "Helm release name for External Secrets, which is also its ServiceAccount name and must match the federated credential subject."
  type        = string
  default     = "external-secrets"
}

variable "external_secrets_chart_version" {
  description = "external-secrets chart version."
  type        = string
}

variable "ingress_nginx_chart_version" {
  description = "ingress-nginx chart version."
  type        = string
}

# ---- Monitoring -------------------------------------------------------------

variable "monitoring_enabled" {
  description = "Install kube-prometheus-stack, and turn on ingress-nginx's metrics endpoint and ServiceMonitor."
  type        = bool
  default     = true
}

variable "monitoring_chart_version" {
  description = "prometheus-community/kube-prometheus-stack chart version."
  type        = string
  default     = "88.2.0"
}

variable "monitoring_namespace" {
  description = "Namespace for Prometheus, Grafana and Alertmanager."
  type        = string
  default     = "monitoring"
}

variable "monitoring_retention" {
  description = "How long Prometheus keeps samples. Chart default is 120h; short is fine here because storage is emptyDir and nothing outlives the demo."
  type        = string
  default     = "6h"
}

variable "grafana_admin_password" {
  description = "Grafana admin password. Generated by the root module and also written to Key Vault."
  type        = string
  sensitive   = true
  default     = ""
}

variable "cluster_secret_store_name" {
  description = "Name of the ClusterSecretStore. Must match secretStoreRef.name in helm-chart/templates/secrets.yaml."
  type        = string
  default     = "cluster-secret-store"
}

variable "key_vault_uri" {
  description = "Key Vault data-plane URI the store reads from."
  type        = string
}

variable "workload_identity_client_id" {
  description = "Client ID of the user-assigned identity External Secrets federates to."
  type        = string
}

variable "tenant_id" {
  description = "Entra ID tenant ID."
  type        = string
}

# ---- Application namespace --------------------------------------------------

variable "app_namespace" {
  description = "Namespace the application and its database live in. Created here so MongoDB and the app charts land in the same place."
  type        = string
  default     = "sg-bank"
}

# ---- MongoDB ----------------------------------------------------------------

variable "mongodb_enabled" {
  description = "Install the bitnami MongoDB chart."
  type        = bool
  default     = true
}

variable "mongodb_chart_version" {
  description = "bitnami/mongodb chart version."
  type        = string
  default     = "19.1.25"
}

variable "mongodb_release_name" {
  description = "Helm release name. Drives the Service DNS the connection string points at."
  type        = string
  default     = "mongodb"
}

variable "mongodb_replica_count" {
  description = "Members in the replica set. Three gives an odd number of voters without an arbiter."
  type        = number
  default     = 3
}

variable "mongodb_replica_set_name" {
  description = "Replica set name; must match the replicaSet parameter in the connection string."
  type        = string
  default     = "rs0"
}

variable "mongodb_resources_preset" {
  description = "bitnami resources preset. 'small' is 500m/512Mi requested per member; 'micro' is 250m/256Mi but risks OOM, since MongoDB sizes its WiredTiger cache at 256MB minimum."
  type        = string
  default     = "small"
}

variable "mongodb_storage_size" {
  description = "PVC size per member."
  type        = string
  default     = "8Gi"
}

variable "mongodb_database" {
  description = "Application database name."
  type        = string
}

variable "mongodb_username" {
  description = "Application user. Gets readWrite on mongodb_database."
  type        = string
}

variable "mongodb_password" {
  description = "Application user password."
  type        = string
  sensitive   = true
}

variable "mongodb_root_password" {
  description = "Root password. Used to bootstrap the set; the application never authenticates with it."
  type        = string
  sensitive   = true
}

variable "mongodb_replica_set_key" {
  description = "Shared key members use to authenticate to each other."
  type        = string
  sensitive   = true
}
