/**
 * Create / edit form.
 *
 * Client-side validation here is UX only. Every rule is enforced again on the
 * server, and the server's per-field errors are what populate the inline
 * messages below - so the two can never silently drift apart.
 */
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../api/client.js';
import { Alert, Button, Card, Field, Spinner } from '../components/ui.jsx';

const TYPES = ['SAVINGS', 'CURRENT', 'FIXED_DEPOSIT', 'JOINT'];
const CURRENCIES = ['EUR', 'USD', 'GBP', 'INR', 'CHF'];

const EMPTY = {
  holderName: '',
  email: '',
  phone: '',
  address: '',
  accountType: 'CURRENT',
  currency: 'EUR',
  branchCode: '',
  initialDeposit: '0',
};

export default function AccountFormPage() {
  const { id } = useParams();
  const isEdit = Boolean(id);
  const navigate = useNavigate();

  const [form, setForm] = useState(EMPTY);
  const [version, setVersion] = useState(null);
  const [loading, setLoading] = useState(isEdit);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [fieldErrors, setFieldErrors] = useState({});

  useEffect(() => {
    if (!isEdit) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await api.getAccount(id);
        if (cancelled) return;
        setForm({
          holderName: res.data.holderName ?? '',
          email: res.data.email ?? '',
          phone: res.data.phone ?? '',
          address: res.data.address ?? '',
          accountType: res.data.accountType,
          currency: res.data.balance.currency,
          branchCode: res.data.branchCode,
          initialDeposit: String(res.data.balance.amount),
        });
        setVersion(res.data.version);
      } catch (err) {
        if (!cancelled) setError(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id, isEdit]);

  const set = (key) => (event) => setForm((f) => ({ ...f, [key]: event.target.value }));

  async function onSubmit(event) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    setFieldErrors({});

    try {
      if (isEdit) {
        // Only the mutable fields are sent. Status and balance are not part of
        // this payload by design - the API would reject them anyway.
        const res = await api.updateAccount(id, {
          holderName: form.holderName.trim(),
          email: form.email.trim(),
          phone: form.phone.trim() || null,
          address: form.address.trim() || null,
          accountType: form.accountType,
          branchCode: form.branchCode.trim().toUpperCase(),
          expectedVersion: version,
        });
        navigate(`/accounts/${res.data.id}`, { replace: true });
      } else {
        const res = await api.createAccount({
          holderName: form.holderName.trim(),
          email: form.email.trim(),
          ...(form.phone.trim() ? { phone: form.phone.trim() } : {}),
          ...(form.address.trim() ? { address: form.address.trim() } : {}),
          accountType: form.accountType,
          currency: form.currency,
          branchCode: form.branchCode.trim().toUpperCase(),
          initialDeposit: form.initialDeposit || '0',
        });
        navigate(`/accounts/${res.data.id}`, { replace: true });
      }
    } catch (err) {
      setError(err.message);
      setFieldErrors(err.fieldErrors ?? {});
    } finally {
      setBusy(false);
    }
  }

  if (loading) return <Spinner label="Loading account" />;

  return (
    <div className="page page--narrow">
      <div className="page__head">
        <div>
          <h1 className="page__title">{isEdit ? 'Edit account' : 'Open a new account'}</h1>
          <p className="page__lede">
            {isEdit
              ? 'Changes are versioned and recorded in the audit trail.'
              : 'The account number is generated by the system as a valid French IBAN.'}
          </p>
        </div>
      </div>

      <Card>
        {error && (
          <Alert tone="error" title="Could not save">
            {error}
          </Alert>
        )}

        <form className="form" onSubmit={onSubmit} noValidate>
          <div className="form__grid">
            <Field
              label="Account holder"
              htmlFor="holderName"
              required
              error={fieldErrors.holderName}
            >
              <input
                id="holderName"
                className="input"
                value={form.holderName}
                onChange={set('holderName')}
                maxLength={120}
                required
                autoComplete="off"
              />
            </Field>

            <Field label="E-mail" htmlFor="email" required error={fieldErrors.email}>
              <input
                id="email"
                className="input"
                type="email"
                value={form.email}
                onChange={set('email')}
                maxLength={254}
                required
                autoComplete="off"
              />
            </Field>

            <Field label="Phone" htmlFor="phone" error={fieldErrors.phone} hint="Optional">
              <input
                id="phone"
                className="input"
                value={form.phone}
                onChange={set('phone')}
                maxLength={24}
                autoComplete="off"
              />
            </Field>

            <Field label="Branch code" htmlFor="branchCode" required error={fieldErrors.branchCode}>
              <input
                id="branchCode"
                className="input input--mono"
                value={form.branchCode}
                onChange={set('branchCode')}
                placeholder="PAR001"
                maxLength={10}
                required
                autoComplete="off"
              />
            </Field>

            <Field label="Account type" htmlFor="accountType" required error={fieldErrors.accountType}>
              <select id="accountType" className="select" value={form.accountType} onChange={set('accountType')}>
                {TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t.replace('_', ' ')}
                  </option>
                ))}
              </select>
            </Field>

            <Field
              label="Currency"
              htmlFor="currency"
              error={fieldErrors.currency}
              hint={isEdit ? 'Currency cannot be changed after opening' : undefined}
            >
              <select
                id="currency"
                className="select"
                value={form.currency}
                onChange={set('currency')}
                disabled={isEdit}
              >
                {CURRENCIES.map((c) => (
                  <option key={c} value={c}>
                    {c}
                  </option>
                ))}
              </select>
            </Field>

            {!isEdit && (
              <Field
                label="Initial deposit"
                htmlFor="initialDeposit"
                error={fieldErrors.initialDeposit}
                hint="Stored in minor units — no floating-point rounding"
              >
                <input
                  id="initialDeposit"
                  className="input input--mono"
                  inputMode="decimal"
                  value={form.initialDeposit}
                  onChange={set('initialDeposit')}
                  maxLength={16}
                />
              </Field>
            )}

            <Field
              label="Address"
              htmlFor="address"
              error={fieldErrors.address}
              hint="Optional"
            >
              <textarea
                id="address"
                className="input textarea"
                rows={2}
                value={form.address}
                onChange={set('address')}
                maxLength={200}
              />
            </Field>
          </div>

          <div className="form__actions">
            <Button variant="ghost" onClick={() => navigate(-1)}>
              Cancel
            </Button>
            <Button type="submit" busy={busy}>
              {isEdit ? 'Save changes' : 'Open account'}
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
